# GENERATED BY Accumulate gen-sdk. DO NOT EDIT.

"""Type definitions for Accumulate API"""

import base64
from datetime import datetime
from enum import Enum
from typing import Optional, List, Dict, Any, Union
from dataclasses import dataclass, field

