#!/usr/bin/env python3
"""
Example 15: Co-Signing to Satisfy an M-of-N Threshold

A signature threshold is satisfied by DISTINCT keys signing the SAME
transaction. Signing the same body twice does NOT work: the first signature's
metadata becomes the transaction's `initiator` and is baked into the header, so
a second independent signature covers a different transaction hash and neither
copy reaches the threshold.

The flow is: sign once to build an envelope, co-sign that envelope with each
additional key, then submit ONCE. Submitting between signatures trips replay
protection on the signature already on chain.

This example builds a 2-of-3 key book and then creates a data account governed
by it. That creation needs BOTH authorities to approve: the parent ADI's own
book (it owns the namespace) and the multi-sig book being installed -- three
signatures on one envelope. Note the first key signs twice, under two different
pages: a signature is identified by (key, signer), so those are distinct and
satisfy two separate authorities.
"""

"""
Multi-Signature Setup
=====================

Generated by Accumulate Studio
Network: kermit
"""

import time

from accumulate_client import Accumulate, NetworkStatusOptions
from accumulate_client.convenience import TxBody, SmartSigner
from accumulate_client.crypto.ed25519 import Ed25519KeyPair
import hashlib
import requests as _requests_lib

# Network endpoints
NETWORK_ENDPOINT = "https://kermit.accumulatenetwork.io"
# For local DevNet testing, uncomment:
# NETWORK_ENDPOINT = "http://127.0.0.1:26660"


def fund_account(client, account_url, faucet_requests=1):
    """Fund an account using the testnet faucet with retry logic."""
    v2_endpoint = client.v2.endpoint
    print(f"Requesting funds from faucet ({faucet_requests} times)...")
    for i in range(faucet_requests):
        try:
            response = _requests_lib.post(
                v2_endpoint,
                json={
                    "jsonrpc": "2.0",
                    "method": "faucet",
                    "params": {"url": account_url},
                    "id": i + 1,
                },
                timeout=30,
            )
            result = response.json()
            txid = result.get("result", {}).get("txid", "submitted")
            print(f"  Faucet {i+1}/{faucet_requests}: {str(txid)[:40]}...")
            time.sleep(2)
        except Exception as e:
            print(f"  Faucet {i+1}/{faucet_requests} failed: {e}")


def poll_for_balance(client, account_url, min_balance=1, max_attempts=30):
    """Poll until account balance meets minimum threshold."""
    for i in range(max_attempts):
        try:
            result = client.v3.query(account_url)
            balance = result.get("account", {}).get("balance")
            if balance is not None:
                balance_int = int(balance) if isinstance(balance, (int, str)) else 0
                if balance_int > 0 and balance_int >= min_balance:
                    return balance_int
            print(f"  Waiting for balance... (attempt {i+1}/{max_attempts})")
        except Exception:
            pass
        time.sleep(2)
    return 0


def poll_for_credits(client, account_url, min_credits=1, max_attempts=30):
    """Poll until account credit balance meets minimum threshold."""
    for i in range(max_attempts):
        try:
            result = client.v3.query(account_url)
            credits = result.get("account", {}).get("creditBalance", 0)
            if int(credits) > 0 and int(credits) >= min_credits:
                return int(credits)
            print(f"  Waiting for credits... (attempt {i+1}/{max_attempts})")
        except Exception:
            pass
        time.sleep(2)
    return 0


def main():
    """
    Multi-Signature Setup
    Complete multi-sig flow from scratch. Sets up keys, creates an ADI, then creates a dedicated key book with multiple signers and a 2-of-3 threshold.
    Generated by Accumulate Studio
    """

    # Connect to the network
    client = Accumulate(NETWORK_ENDPOINT)
    tx_ids = []

    # Flow variables (customize these for your use case)
    adi_name = f"adi-{int(time.time())}"  # Name for your ADI (e.g., 'my-multisig-adi')

    try:


        # =========================================================
        # Generate Keys (Signer 1) (Action: GenerateKeys)
        # =========================================================
        generate_keys_signer_1_kp = Ed25519KeyPair.generate()
        generate_keys_signer_1_lid = generate_keys_signer_1_kp.derive_lite_identity_url()
        generate_keys_signer_1_lta = generate_keys_signer_1_kp.derive_lite_token_account_url("ACME")
        generate_keys_signer_1_pub_hash = hashlib.sha256(generate_keys_signer_1_kp.public_key_bytes()).hexdigest()
        print(f"Generated keypair:")
        print(f"  Lite Identity: {generate_keys_signer_1_lid}")
        print(f"  Lite Token Account: {generate_keys_signer_1_lta}")

        # =========================================================
        # Request Tokens (Action: Faucet)
        # =========================================================
        fund_account(client, str(generate_keys_signer_1_lta), faucet_requests=3)
        print("Faucet request completed")

        # =========================================================
        # Wait for ACME (Action: WaitForBalance)
        # =========================================================
        print("Waiting for balance >= 15.00000000...")
        _balance = poll_for_balance(client, str(generate_keys_signer_1_lta), min_balance=15.00000000)
        if _balance == 0:
            print("ERROR: Balance did not reach minimum. Stopping.")
            return
        print(f"Balance confirmed: {_balance}")

        # =========================================================
        # Add Credits (Action: AddCredits)
        # =========================================================
        add_credits_oracle = client.v3.network_status(
            NetworkStatusOptions(partition="directory")
        ).get("oracle", {}).get("price", 500000)
        print(f"Oracle price: {add_credits_oracle}")
        add_credits_signer = SmartSigner(client.v3, generate_keys_signer_1_kp, generate_keys_signer_1_lid)
        add_credits_result = add_credits_signer.sign_submit_and_wait(
            principal=str(generate_keys_signer_1_lta),
            body=TxBody.add_credits(
                recipient=str(generate_keys_signer_1_lid),
                amount="1000000000",
                oracle=add_credits_oracle,
            ),
            max_attempts=30,
        )
        if add_credits_result.success:
            print(f"AddCredits SUCCESS - TxID: {add_credits_result.txid}")
            tx_ids.append(("AddCredits", add_credits_result.txid))
        else:
            print(f"AddCredits FAILED: {add_credits_result.error}")

        # =========================================================
        # Wait for Credits (Action: WaitForCredits)
        # =========================================================
        print("Waiting for credits >= 1000...")
        _credits = poll_for_credits(client, str(generate_keys_signer_1_lid), min_credits=1000)
        if _credits == 0:
            print("ERROR: Credits did not reach minimum. Stopping.")
            return
        print(f"Credits confirmed: {_credits}")

        # =========================================================
        # Create ADI (Action: CreateIdentity)
        # =========================================================
        create_adi_url = f"acc://{adi_name}.acme"
        create_adi_signer = SmartSigner(client.v3, generate_keys_signer_1_kp, generate_keys_signer_1_lid)
        create_adi_result = create_adi_signer.sign_submit_and_wait(
            principal=str(generate_keys_signer_1_lta),
            body=TxBody.create_identity(
                url=create_adi_url,
                key_book_url=f"{create_adi_url}/book",
                public_key_hash=generate_keys_signer_1_pub_hash,
            ),
            max_attempts=30,
        )
        if create_adi_result.success:
            print(f"CreateIdentity SUCCESS - TxID: {create_adi_result.txid}")
            tx_ids.append(("CreateIdentity", create_adi_result.txid))
        else:
            print(f"CreateIdentity FAILED: {create_adi_result.error}")

        # =========================================================
        # Credit Key Page (Action: AddCredits)
        # =========================================================
        credit_key_page_oracle = client.v3.network_status(
            NetworkStatusOptions(partition="directory")
        ).get("oracle", {}).get("price", 500000)
        print(f"Oracle price: {credit_key_page_oracle}")
        credit_key_page_signer = SmartSigner(client.v3, generate_keys_signer_1_kp, generate_keys_signer_1_lid)
        credit_key_page_result = credit_key_page_signer.sign_submit_and_wait(
            principal=str(generate_keys_signer_1_lta),
            body=TxBody.add_credits(
                recipient=f"{str(create_adi_url)}/book/1",
                amount="1000000000",
                oracle=credit_key_page_oracle,
            ),
            max_attempts=30,
        )
        if credit_key_page_result.success:
            print(f"AddCredits SUCCESS - TxID: {credit_key_page_result.txid}")
            tx_ids.append(("AddCredits", credit_key_page_result.txid))
        else:
            print(f"AddCredits FAILED: {credit_key_page_result.error}")

        # =========================================================
        # Wait for Key Page Credits (Action: WaitForCredits)
        # =========================================================
        print("Waiting for credits >= 1000...")
        _credits = poll_for_credits(client, f"{str(create_adi_url)}/book/1", min_credits=1000)
        if _credits == 0:
            print("ERROR: Credits did not reach minimum. Stopping.")
            return
        print(f"Credits confirmed: {_credits}")

        # =========================================================
        # Create Multi-Sig Key Book (Action: CreateKeyBook)
        # =========================================================
        create_multi_sig_key_book_url = f"{str(create_adi_url)}/multisig-book"
        create_multi_sig_key_book_signer = SmartSigner(client.v3, generate_keys_signer_1_kp, f"{str(create_adi_url)}/book/1")
        create_multi_sig_key_book_result = create_multi_sig_key_book_signer.sign_submit_and_wait(
            principal=str(create_adi_url),
            body=TxBody.create_key_book(
                url=create_multi_sig_key_book_url,
                public_key_hash=generate_keys_signer_1_pub_hash,
            ),
            max_attempts=30,
        )
        if create_multi_sig_key_book_result.success:
            print(f"CreateKeyBook SUCCESS - TxID: {create_multi_sig_key_book_result.txid}")
            tx_ids.append(("CreateKeyBook", create_multi_sig_key_book_result.txid))
        else:
            print(f"CreateKeyBook FAILED: {create_multi_sig_key_book_result.error}")

        # =========================================================
        # Credit Multi-Sig Key Page (Action: AddCredits)
        # =========================================================
        credit_multi_sig_key_page_oracle = client.v3.network_status(
            NetworkStatusOptions(partition="directory")
        ).get("oracle", {}).get("price", 500000)
        print(f"Oracle price: {credit_multi_sig_key_page_oracle}")
        credit_multi_sig_key_page_signer = SmartSigner(client.v3, generate_keys_signer_1_kp, generate_keys_signer_1_lid)
        credit_multi_sig_key_page_result = credit_multi_sig_key_page_signer.sign_submit_and_wait(
            principal=str(generate_keys_signer_1_lta),
            body=TxBody.add_credits(
                recipient=f"{str(create_adi_url)}/multisig-book/1",
                amount="500000000",
                oracle=credit_multi_sig_key_page_oracle,
            ),
            max_attempts=30,
        )
        if credit_multi_sig_key_page_result.success:
            print(f"AddCredits SUCCESS - TxID: {credit_multi_sig_key_page_result.txid}")
            tx_ids.append(("AddCredits", credit_multi_sig_key_page_result.txid))
        else:
            print(f"AddCredits FAILED: {credit_multi_sig_key_page_result.error}")

        # =========================================================
        # Wait for Multi-Sig Credits (Action: WaitForCredits)
        # =========================================================
        print("Waiting for credits >= 1000...")
        _credits = poll_for_credits(client, f"{str(create_adi_url)}/multisig-book/1", min_credits=1000)
        if _credits == 0:
            print("ERROR: Credits did not reach minimum. Stopping.")
            return
        print(f"Credits confirmed: {_credits}")

        # =========================================================
        # Generate Keys (Signer 2) (Action: GenerateKeys)
        # =========================================================
        generate_keys_signer_2_kp = Ed25519KeyPair.generate()
        generate_keys_signer_2_lid = generate_keys_signer_2_kp.derive_lite_identity_url()
        generate_keys_signer_2_lta = generate_keys_signer_2_kp.derive_lite_token_account_url("ACME")
        generate_keys_signer_2_pub_hash = hashlib.sha256(generate_keys_signer_2_kp.public_key_bytes()).hexdigest()
        print(f"Generated keypair:")
        print(f"  Lite Identity: {generate_keys_signer_2_lid}")
        print(f"  Lite Token Account: {generate_keys_signer_2_lta}")

        # =========================================================
        # Add Signer 2 (Action: UpdateKeyPage)
        # =========================================================
        add_signer_2_signer = SmartSigner(client.v3, generate_keys_signer_1_kp, f"{str(create_adi_url)}/multisig-book/1")
        add_signer_2_result = add_signer_2_signer.sign_submit_and_wait(
            principal=f"{str(create_adi_url)}/multisig-book/1",
            body=TxBody.update_key_page(
                operations=[{"type":"add","entry":{"keyHash":generate_keys_signer_2_pub_hash}}],
            ),
            max_attempts=30,
        )
        if add_signer_2_result.success:
            print(f"UpdateKeyPage SUCCESS - TxID: {add_signer_2_result.txid}")
            tx_ids.append(("UpdateKeyPage", add_signer_2_result.txid))
        else:
            print(f"UpdateKeyPage FAILED: {add_signer_2_result.error}")

        # =========================================================
        # Generate Keys (Signer 3) (Action: GenerateKeys)
        # =========================================================
        generate_keys_signer_3_kp = Ed25519KeyPair.generate()
        generate_keys_signer_3_lid = generate_keys_signer_3_kp.derive_lite_identity_url()
        generate_keys_signer_3_lta = generate_keys_signer_3_kp.derive_lite_token_account_url("ACME")
        generate_keys_signer_3_pub_hash = hashlib.sha256(generate_keys_signer_3_kp.public_key_bytes()).hexdigest()
        print(f"Generated keypair:")
        print(f"  Lite Identity: {generate_keys_signer_3_lid}")
        print(f"  Lite Token Account: {generate_keys_signer_3_lta}")

        # =========================================================
        # Add Signer 3 (Action: UpdateKeyPage)
        # =========================================================
        add_signer_3_signer = SmartSigner(client.v3, generate_keys_signer_1_kp, f"{str(create_adi_url)}/multisig-book/1")
        add_signer_3_result = add_signer_3_signer.sign_submit_and_wait(
            principal=f"{str(create_adi_url)}/multisig-book/1",
            body=TxBody.update_key_page(
                operations=[{"type":"add","entry":{"keyHash":generate_keys_signer_3_pub_hash}}],
            ),
            max_attempts=30,
        )
        if add_signer_3_result.success:
            print(f"UpdateKeyPage SUCCESS - TxID: {add_signer_3_result.txid}")
            tx_ids.append(("UpdateKeyPage", add_signer_3_result.txid))
        else:
            print(f"UpdateKeyPage FAILED: {add_signer_3_result.error}")

        # =========================================================
        # Set Threshold (2 of 3) (Action: UpdateKeyPage)
        # =========================================================
        set_threshold_2_of_3_signer = SmartSigner(client.v3, generate_keys_signer_1_kp, f"{str(create_adi_url)}/multisig-book/1")
        set_threshold_2_of_3_result = set_threshold_2_of_3_signer.sign_submit_and_wait(
            principal=f"{str(create_adi_url)}/multisig-book/1",
            body=TxBody.update_key_page(
                operations=[{"type":"setThreshold","threshold":2}],
            ),
            max_attempts=30,
        )
        if set_threshold_2_of_3_result.success:
            print(f"UpdateKeyPage SUCCESS - TxID: {set_threshold_2_of_3_result.txid}")
            tx_ids.append(("UpdateKeyPage", set_threshold_2_of_3_result.txid))
        else:
            print(f"UpdateKeyPage FAILED: {set_threshold_2_of_3_result.error}")

        # =========================================================
        # Create Data Account Governed by the Multi-Sig Book (Action: CoSign — create_data_account under an M-of-N threshold)
        # =========================================================
        # A threshold needs DISTINCT keys signing the SAME transaction. Signing the
        # body twice does not work: the first signature's metadata becomes the
        # transaction's `initiator` and is baked into the header, so a second
        # independent signature is over a different transaction hash and neither
        # copy reaches the threshold. Co-sign the existing envelope instead.
        create_data_account_governed_by_the_multi_sig_book_body = TxBody.create_data_account(url=f"{str(create_adi_url)}/ms-data", authorities=[f"{str(create_adi_url)}/multisig-book"])
        create_data_account_governed_by_the_multi_sig_book_signer = SmartSigner(client.v3, generate_keys_signer_1_kp, f"{str(create_adi_url)}/book/1")
        create_data_account_governed_by_the_multi_sig_book_envelope = create_data_account_governed_by_the_multi_sig_book_signer.sign_and_build(
            principal=str(create_adi_url),
            body=create_data_account_governed_by_the_multi_sig_book_body,
        )
        # Co-signer 0: appends a signature to the SAME transaction hash.
        create_data_account_governed_by_the_multi_sig_book_envelope = SmartSigner(client.v3, generate_keys_signer_1_kp, f"{str(create_adi_url)}/multisig-book/1").sign_existing(
            create_data_account_governed_by_the_multi_sig_book_envelope
        )
        # Co-signer 1: appends a signature to the SAME transaction hash.
        create_data_account_governed_by_the_multi_sig_book_envelope = SmartSigner(client.v3, generate_keys_signer_2_kp, f"{str(create_adi_url)}/multisig-book/1").sign_existing(
            create_data_account_governed_by_the_multi_sig_book_envelope
        )
        # Submit only once every signature is collected: resubmitting a signature
        # that is already on chain trips replay protection.
        create_data_account_governed_by_the_multi_sig_book_result = client.submit(create_data_account_governed_by_the_multi_sig_book_envelope)
        create_data_account_governed_by_the_multi_sig_book_messages = create_data_account_governed_by_the_multi_sig_book_result if isinstance(create_data_account_governed_by_the_multi_sig_book_result, list) else [create_data_account_governed_by_the_multi_sig_book_result]
        create_data_account_governed_by_the_multi_sig_book_failed = [
            ((s.get("status") or {}).get("error") or {}).get("message", "unknown")
            for s in create_data_account_governed_by_the_multi_sig_book_messages
            if isinstance(s, dict) and (
                (s.get("status") or {}).get("failed")
                or ((s.get("status") or {}).get("error") is not None)
            )
        ]
        # The transaction's own txID is the one whose principal is the target
        # account; the others belong to the signature messages.
        create_data_account_governed_by_the_multi_sig_book_txid = next(
            (
                (s.get("status") or {}).get("txID", "")
                for s in create_data_account_governed_by_the_multi_sig_book_messages
                if isinstance(s, dict) and (s.get("status") or {}).get("txID")
            ),
            "",
        )
        if create_data_account_governed_by_the_multi_sig_book_failed:
            print(f"CoSign create_data_account FAILED: {create_data_account_governed_by_the_multi_sig_book_failed}")
        else:
            # Acceptance is not execution. A transaction that has not reached its
            # threshold is accepted with code "ok" and then sits pending, so the
            # only honest confirmation is the delivered status.
            create_data_account_governed_by_the_multi_sig_book_status = "unknown"
            for _ in range(30):
                try:
                    create_data_account_governed_by_the_multi_sig_book_q = client.query(create_data_account_governed_by_the_multi_sig_book_txid)
                    # V3 reports status as a string; V2 as a dict with a flag.
                    create_data_account_governed_by_the_multi_sig_book_raw = (create_data_account_governed_by_the_multi_sig_book_q or {}).get("status")
                    create_data_account_governed_by_the_multi_sig_book_status = (
                        create_data_account_governed_by_the_multi_sig_book_raw
                        if isinstance(create_data_account_governed_by_the_multi_sig_book_raw, str)
                        else ("delivered" if (create_data_account_governed_by_the_multi_sig_book_raw or {}).get("delivered") else "pending")
                    )
                    if create_data_account_governed_by_the_multi_sig_book_status not in ("pending", "unknown"):
                        break
                except Exception:
                    pass
                time.sleep(2)
            if create_data_account_governed_by_the_multi_sig_book_status == "delivered":
                print(f"CoSign create_data_account DELIVERED with 3 signature(s) - TxID: {create_data_account_governed_by_the_multi_sig_book_txid}")
                tx_ids.append(("CoSign:create_data_account", create_data_account_governed_by_the_multi_sig_book_txid))
            else:
                print(f"CoSign create_data_account NOT DELIVERED (status={create_data_account_governed_by_the_multi_sig_book_status}) - TxID: {create_data_account_governed_by_the_multi_sig_book_txid}")


        # =========================================================
        # Summary
        # =========================================================
        print("\n=== TRANSACTION IDs FOR VERIFICATION ===\n")
        for tx_name, txid in tx_ids:
            print(f"  {tx_name}: {txid}")
        print(f"\nTotal transactions: {len(tx_ids)}")
        print("Flow completed successfully!")

    finally:
        client.close()


if __name__ == "__main__":
    main()
